//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Discussions = new HashSet<Discussion>();
        }
    
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> SuperCommentId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual ICollection<Discussion> Discussions { get; set; }
    }
}
