//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Discussions = new HashSet<Discussion>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TimeUploaded { get; set; }
        public string Type { get; set; }
        public string Md5String { get; set; }
        public Nullable<int> SuperItemId { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Place { get; set; }
    
        public virtual ICollection<Discussion> Discussions { get; set; }
        public virtual User User { get; set; }
    }
}
